# Generated by Django 6.0.4 on 2026-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articleseries',
            options={'ordering': ['-published_at'], 'verbose_name_plural': 'Series'},
        ),
    ]
